### ISSUE TITLE
Question about output values

### ISSUE THREAD

**Issue by amjayage** [phugh/bigfive#1]
Hi, can I check if the output values for the OCEAN traits are normalized to fall between a certain range?

Thanks.

**Comment by phughesmcr** [comment]
Hi, I'm almost certain they are not normalised, though it has been a while since I read the [original paper](https://storage.googleapis.com/plos-corpus-prod/10.1371/journal.pone.0073791/1/pone.0073791.pdf?X-Goog-Algorithm=GOOG4-RSA-SHA256&X-Goog-Credential=wombat-sa%40plos-prod.iam.gserviceaccount.com%2F20210612%2Fauto%2Fstorage%2Fgoog4_request&X-Goog-Date=20210612T121625Z&X-Goog-Expires=86400&X-Goog-SignedHeaders=host&X-Goog-Signature=81ac25130c6e45b2dc51ba04ef62a29c2d453e236a9debcaaac8bd62697bdc8fc0af62f231817423d37d8c22664f03e640f70703effb85172f6dc38130093675338d1ddb318d9a30eb025d6c169b159384908913b5354ff0ad0b7a02544b36da42b429f91393e45ef178138a719e1894d17dafb3a301c7cae0fbd370259b0f9c57bf8908a6d7472b7dbd37cb2f6816e44733d410376fd28b6f6a642ba5f0976e6f4c2c2336d8a11081b42b98298a9306d13220374f86a72089c97d9d121af321df42d88dcc7a74cba7f28a81330145dab96af12ce7355092714e3771bf081d08af169864e059572bb0707a15c3085c496d3d667bb6c3753e49fcb171ba568432)
